### ISSUE TITLE
I can't integrate your wonderful library into my react native

### ISSUE THREAD

**Issue by YOEL311** [ryanseys/lune#28]
Hello
I can't integrate your wonderful library into my react native project
I'm getting an error

error

error: bundling failed: Error: Unable to resolve module `lune` from `D:\projeckts\compass-react-native-non-expo-master\src\Compass.js`: Module `lune` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\lib\transformHelpers.js:264:42)
    at dependencies.map.result (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\projeckts\compass-react-native-non-expo-master\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

package.json

{
  "name": "CompassReactNative",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "luna": "^1.6.3",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-easy-grid": "^0.2.1",
    "react-native-sensors": "^5.3.0",
    "suncalc": "^1.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by ironwallaby** [comment]
I'm afraid I can't help here! It looks like the error is happening outside this project, and I'm afraid I don't know anything about `react-native`. Sorry :(

**Comment by YOEL311** [comment]
I will never forgive myself for this mistake
I wrote LUNA instead of LUNE
